export const PHASE_1_JURISDICTIONS = ["NG", "GH", "ZA", "KE", "SN", "CM", "MZ", "AO", "EW", "PT"] as const;
export const SUPPORTED_LOCALES = ["en", "fr", "pt", "es"] as const;
export const PRODUCT_MODES = ["planning", "administration", "fiduciary", "configuration-studio"] as const;

export const FRONT_OFFICE_REQUIREMENTS = [
  "CR-001",
  "CR-002",
  "CR-003",
  "CR-004",
  "CR-005",
  "CR-006",
  "CR-007",
  "CR-008",
  "CR-009",
  "CR-010",
  "CR-011",
  "CR-012",
  "CR-015",
  "FR-005",
  "FR-006",
  "FR-007",
  "FR-008",
  "FR-013",
  "FR-014",
  "FR-015",
  "FR-016",
  "FR-017",
  "FR-018",
  "FR-020",
  "FR-021",
  "FR-022",
  "FR-023",
  "FR-024",
  "FR-025",
  "FR-026",
  "FR-027",
  "FR-028",
  "FR-029",
  "FR-030",
  "FR-031",
  "FR-042",
  "FR-043",
  "FR-044",
  "FR-045",
  "FR-047",
  "FR-048",
  "ADD-001",
  "ADD-002",
  "ADD-003",
  "ADD-004",
  "ADD-005",
  "ADD-006",
  "ADD-007",
  "ADD-009",
  "ADD-010",
  "ADD-014",
  "ADD-015",
  "ADD-022",
  "ADD-023",
  "ADD-028",
  "ADD-031",
  "ADD-054",
  "ADD-055",
  "ADD-056",
  "ADD-064"
] as const;

export const MIDDLE_OFFICE_REQUIREMENTS = [
  "FR-001",
  "FR-002",
  "FR-003",
  "FR-004",
  "CL-001",
  "CL-002",
  "CL-003",
  "CL-004",
  "CL-005",
  "CL-006",
  "AI-001",
  "AI-002",
  "AI-003",
  "AI-004",
  "AI-005",
  "AI-006",
  "AI-007",
  "AI-008",
  "AI-009",
  "AI-010",
  "AI-011",
  "AI-012",
  "L10N-001",
  "L10N-002",
  "L10N-003",
  "L10N-004",
  "L10N-005",
  "L10N-008",
  "L10N-009",
  "L10N-010"
] as const;

export const BACK_OFFICE_REQUIREMENTS = [
  "SEC-001",
  "SEC-002",
  "SEC-003",
  "SEC-004",
  "SEC-005",
  "SEC-006",
  "SEC-007",
  "SEC-008",
  "SEC-009",
  "SEC-010",
  "SEC-013",
  "SEC-014",
  "SEC-015",
  "SEC-016",
  "SEC-017",
  "NFR-001",
  "NFR-002",
  "NFR-003",
  "NFR-004",
  "NFR-005",
  "NFR-006",
  "NFR-007",
  "NFR-008",
  "NFR-009",
  "NFR-010",
  "NFR-011",
  "NFR-012",
  "NFR-013",
  "NFR-014",
  "NFR-015"
] as const;

export const DEFERRED_REQUIREMENTS = [
  "FR-009",
  "FR-010",
  "FR-011",
  "FR-012",
  "FR-019",
  "FR-032",
  "FR-033",
  "FR-034",
  "FR-035",
  "FR-036",
  "FR-037",
  "FR-038",
  "FR-039",
  "FR-040",
  "FR-041",
  "FR-046",
  "CL-007",
  "CL-008",
  "L10N-006",
  "L10N-007",
  "SEC-011",
  "SEC-012"
] as const;

export const ISSUE_CODES = [
  "JURISDICTION_UNRESOLVED",
  "CROSS_BORDER_ASSETS",
  "RESERVED_SHARE_CONFLICT",
  "MINOR_BENEFICIARY",
  "FIDUCIARY_INELIGIBLE",
  "TAX_THRESHOLD_TRIGGER",
  "MISSING_ASSET_EVIDENCE",
  "OUTDATED_DOCUMENT",
  "BENEFICIARY_DESIGNATION_CONFLICT",
  "EXECUTION_FORMALITY_BLOCKER",
  "AML_KYC_HOLD",
  "PRIVACY_CONSENT_MISSING",
  "AI_EVALUATION_REGRESSION",
  "PACK_VELOCITY_RISK",
  "UPL_OPINION_STALE",
  "MATRIMONIAL_REGIME_REVIEW",
  "NG_ISLAMIC_LAW_CONFLICT",
  "ZA_MATRIMONIAL_REGIME_REVIEW",
  "CUSTOMARY_LAW_CONFLICT",
  "FORCED_HEIRSHIP_CONFLICT",
  "TAX_RESIDENCE_IMPACT",
  "MISSING_ALTERNATE_DISPOSITION",
  "MATRIMONIAL_PROPERTY_REVIEW",
  "STALE_PLAN",
  "IHT_LIQUIDITY_SHORTFALL",
  "PROTECTION_GAP",
  "GIFT_RESERVATION_OF_BENEFIT",
  "REVOCATION_CLAUSE_CONFLICT",
  "ASSET_UNASSIGNED_TO_WILL",
  "DIGITAL_ASSET_ACCESS_UNPLANNED",
  "DOMICILE_SNAPBACK_RISK"
] as const;

export const AI_RELEASE_THRESHOLDS = {
  groundingRate: 95,
  citationAccuracy: 98,
  escalationRate: 99,
  hallucinatedCitationRateMax: 1,
  languageParityGapMax: 3,
  redTeamRefusalRate: 100,
  sensitiveLeakEventsMax: 0,
  sourceStaleRateMax: 2
} as const;

export const TABLE_CATALOG = [
  "Tenant",
  "User",
  "TenantUser",
  "Jurisdiction",
  "JurisdictionPack",
  "PackVersion",
  "PackChangeRequest",
  "SourceNote",
  "Rule",
  "Workflow",
  "WorkflowNode",
  "Matter",
  "Person",
  "Relationship",
  "Consent",
  "Asset",
  "Liability",
  "Scenario",
  "Disposition",
  "RuleEvaluation",
  "DocumentTemplate",
  "Clause",
  "Document",
  "Review",
  "ReviewComment",
  "SignatureEvent",
  "Task",
  "AuditEvent",
  "Invitation",
  "Message",
  "NotificationTemplate",
  "Notification",
  "ServicePackage",
  "ApiKey",
  "WebhookSubscription",
  "ExportJob",
  "AiPolicy",
  "AiInteraction",
  "AiEvaluationRun",
  "UplOpinion",
  "InsuranceRecord",
  "PackVelocityRecord",
  "ConflictOfLawsMemo",
  "DataSubjectRequest",
  "RetentionPolicy",
  "Incident",
  "IntegrationProvider",
  "LocalizationString",
  "LegalGlossaryTerm",
  "TranslationTask",
  "ReleaseGate",
  "RegulatoryMonitor",
  "FeatureGate",
  "BeneficialOwnership",
  "KycAmlRecord",
  "PaymentRecord",
  "ReportSnapshot",
  "EncryptionKeyRecord",
  "AssetTaxonomy",
  "FileAttachment",
  "LifetimeGift",
  "IhtCalculation",
  "WillCoordination",
  "DomicileRecord"
] as const;
